
stages:
  # - mock
  # - 单元测试
  - 产物测试

only:
  triggerType:
    - pullRequest
    - push
    - tagPush

STCa扫描:
  stage: 产物测试
  script: # 执行脚本
    - |
      ls
      echo 1

STCb扫描:
  stage: 产物测试
  script: # 执行脚本
    - |
      ls
      echo 2
